"""Renewed synth power board: synchronous positive buck, negative inverter and LDOs.

U2 provides nominal +13.44 V for LT1963A U6. U3 remains LM2596S-ADJ,
retargeted to +6.519 V for LT1963A U7. U4 remains the inverting LM2596,
retargeted to -14.145 V for adjustable LT3015 U8, set to nominal -12.054 V. Divider tolerances, source locks,
startup and installed thermal/loop limits remain explicit in component evidence.

U4 pins 3/5/6 ride the negative intermediate; its inductor L3.2 returns to
system ground. LT3015 pins 3/6 are the negative input and thermal tab, pin 2
is system ground, pin 5 is output, pin 4 is the ADJ divider midpoint set by
R26/R27/R28, and pin 1 enables from input.
LT1963A pins 1/2 connect to its positive intermediate, pins 3/6 to ground,
pin 4 is output and pin 5 is the precision divider midpoint.

J5 mates the separate PD module, retaining pins 1/2 input, 3 ATT, 4 PDOK,
5/6 GND. J10/J11 are keyed C4749189 outputs: pin 1/2 is -12 V/red stripe.
No printed socket guards or guard-shaped edge notches are needed.

The old netlist baseline remains historical. Intentional renewal differences
are recorded in baselines/board-b-allow.json and decisions.json. Legacy root
v4 files are never regenerated by this spec.
"""

PROJECT_NAME = 'board-b'
OUT = 'boards/board-b/board-b.kicad_sch'
PAPER = 'A1'

_C100N = ('CC0805KRX7R9BB104', '100nF 50V', 'C1711', 'zudo-pd:C0805')
_C470N = ('CL10B474KA8NNNC', '470nF', 'C1623', 'zudo-pd:C0603')
_C470U_35 = ('EFVH035ADA471M10B0', '470uF 35V', 'C22387780', 'zudo-pd:CAP-SMD_BD10.0-L10.3-W10.3-LS11.0-FD')
# Phi 8 can (datasheet: "D8H10.5mm"), NOT the Phi 10 land the other 470uF line uses -- see issue #150
_C470U_25 = ('GVT1E477M0810CNVC', '470uF 25V', 'C2983319', 'zudo-pd:CAP-SMD_BD8.0-L8.3-W8.3-LS9.0-FD')
_C470U_10 = ('RVT1A471M0607_C335982', '470uF 10V', 'C335982', 'zudo-pd:CAP-SMD_BD6.3-L6.6-W6.6-FD')
_C22N = ('CL21B223KBANNNC', '22nF', 'C1729', 'zudo-pd:C0805')
_R1K_LED = ('0805W8F1001T5E', '1k', 'C17513', 'zudo-pd:R0805')
_LM2596 = ('LM2596S-ADJ', 'LM2596S-ADJ', 'C347423', 'zudo-pd:TO-263-5_L10.2-W8.9-P1.70-BR')
_SS34 = ('SS34_C8678', 'SS34', 'C8678', 'zudo-pd:SMA_L4.3-W2.6-LS5.2-RD')
_L100U = ('CYA1265-100UH', '100uH', 'C19268674', 'zudo-pd:IND-SMD_L13.8-W12.8')
_SMAJ15A = ('SMAJ15A_C571368', 'SMAJ15A', 'C571368', 'zudo-pd:D-FLAT_L4.3-W2.6-LS5.3-RD')
_SCREW = ('WJ500V-5.08-2P', 'WJ500V-5.08-2P', 'C8465', 'zudo-pd:WJ500V-5.08-2P_C8465')
_EURO16 = ('DW254P-2X8-L0', 'DW254P-2X8-L0', 'C4749189', 'zudo-pd:IDC-TH_16P-P2.54_321016RG0ABK00A01')
_C10U_50 = ('GRM32ER71H106KA12L', '10uF 50V X7R', 'C77102', 'zudo-pd:C1210')

# A1 presentation grid: 88.9 mm column pitch, 76.2 mm left origin. The
# generous horizontal gutters keep full global net names inside the sheet and
# separate opposing pin labels in adjacent component cells. Electrical fields
# and symbol/footprint identities are independent of these display coordinates.
COMPONENTS = {
    # DC-DC power path (row A)
    'U2':   ('AP63201WU-7', 'AP63201WU-7', 'C2071044', 'zudo-pd:TSOT-23-6_L2.9-W1.6-P0.95-LS2.8-BR', False, (76.2, 50.8)),
    'L1':   ('ASPI-0630LR-100M-T15', '10uH', 'C1334133', 'zudo-pd:ASPI-0630LR_L7.5-W6.85', False, (254, 50.8)),
    'U3':   (*_LM2596, False, (342.9, 50.8)),
    'D2':   (*_SS34, False, (431.8, 50.8)),
    'L2':   (*_L100U, False, (520.7, 50.8)),
    'U4':   (*_LM2596, False, (609.6, 50.8)),
    'D3': ('SDT5A60SA-13', 'SDT5A60SA-13', 'C3024223', 'zudo-pd:SMA_Diodes_SDT5A60SA_C3024223', False, (698.5, 50.8)),
    'L3':   (*_L100U, False, (787.4, 50.8)),
    # LDOs + protection (row B)
    'U6':   ('LT1963AEQ#TRPBF', 'LT1963AEQ#TRPBF', 'C459702', 'zudo-pd:TO-263-5_L10.6-W9.6-P1.70-LS15.9-BR', False, (76.2, 101.6)),
    'U7':   ('LT1963AEQ#TRPBF', 'LT1963AEQ#TRPBF', 'C459702', 'zudo-pd:TO-263-5_L10.6-W9.6-P1.70-LS15.9-BR', False, (165.1, 101.6)),
    'U8':   ('LT3015EQ#PBF', 'LT3015EQ#PBF', 'C666306', 'zudo-pd:DD-PAK-5_L10.2-W8.9-P1.70-LS14.0-BR', False, (254, 101.6)),
    'PTC1': ('SMD1210P150TF/16', 'SMD1210P150TF/16', 'C7529589', 'zudo-pd:F1210', False, (342.9, 101.6)),
    'PTC2': ('mSMD110-33V', 'mSMD110-33V', 'C70119', 'zudo-pd:F1812', False, (431.8, 101.6)),
    'PTC3': ('BSMD1206-150-16V', 'BSMD1206-150-16V', 'C883133', 'zudo-pd:F1206', False, (520.7, 101.6)),
    'TVS1': (*_SMAJ15A, False, (609.6, 101.6)),
    'TVS2': ('SMAJ6.5A_C87267', 'SMAJ6.5A', 'C87267', 'zudo-pd:D-FLAT_L4.3-W2.6-LS5.3-RD', False, (698.5, 101.6)),
    'TVS3': (*_SMAJ15A, False, (787.4, 101.6)),
    # DC-DC stage capacitors (row C)
    'C3':   (*_C10U_50, False, (76.2, 152.4)),
    'C4':   (*_C470U_10, False, (165.1, 152.4)),
    'C5':   (*_C470U_35, False, (254, 152.4)),
    'C6':   (*_C100N, False, (342.9, 152.4)),
    'C7':   (*_C470U_35, False, (431.8, 152.4)),
    'C8':   (*_C100N, False, (520.7, 152.4)),
    'C9':   ('RVT1H101M0810', '100uF 50V', 'C970687', 'zudo-pd:CAP-SMD_BD8.0-L8.3-W8.3-LS9.0-FD', False, (609.6, 152.4)),
    'C10':  (*_C100N, False, (698.5, 152.4)),
    'C11':  (*_C470U_25, False, (787.4, 152.4)),
    # LDO stage capacitors (rows D-E)
    'C14':  (*_C10U_50, False, (76.2, 203.2)),
    'C15':  (*_C470N, False, (165.1, 203.2)),
    'C16':  (*_C470N, False, (254, 203.2)),
    'C17':  (*_C100N, False, (342.9, 203.2)),
    'C18':  (*_C100N, False, (431.8, 203.2)),
    'C19':  (*_C100N, False, (520.7, 203.2)),
    'C20':  (*_C10U_50, False, (609.6, 203.2)),
    'C21':  (*_C470U_35, False, (698.5, 203.2)),
    'C22':  (*_C470U_10, False, (787.4, 203.2)),
    'C23':  (*_C470U_10, False, (76.2, 254)),
    'C24':  (*_C470U_35, False, (165.1, 254)),
    'C25':  (*_C470U_35, False, (254, 254)),
    # feedforward caps + feedback dividers (rows E-F)
    'C32':  (*_C22N, False, (431.8, 254)),
    'C33':  (*_C22N, False, (520.7, 254)),
    'R1':   ('RT0603BRE07158KL', '158k 0.1%', 'C861679', 'zudo-pd:R0603', False, (609.6, 254)),
    'R2':   ('RT0603BRD0710KL', '10k 0.1%', 'C95204', 'zudo-pd:R0603', False, (698.5, 254)),
    'R3':   ('0603WAF4301T5E', '4300R', 'C23159', 'zudo-pd:R0603', False, (787.4, 254)),
    'R4':   ('0603WAF1001T5E', '1k', 'C21190', 'zudo-pd:R0603', False, (76.2, 304.8)),
    'R5':   ('RT0603BRD0710K5L', '10500R', 'C861077', 'zudo-pd:R0603', False, (165.1, 304.8)),
    'R6':   ('RT0603BRD071KL', '1000R', 'C110776', 'zudo-pd:R0603', False, (254, 304.8)),
    # rail indicators (row F)
    'R7':   (*_R1K_LED, False, (342.9, 304.8)),
    'R8':   (*_R1K_LED, False, (431.8, 304.8)),
    'R9':   (*_R1K_LED, False, (520.7, 304.8)),
    'LED2': ('KT-0603YG', 'Green', 'C2289', 'zudo-pd:LED0603-RD', False, (609.6, 304.8)),
    'LED3': ('KT-0603B', 'Blue', 'C2288', 'zudo-pd:LED0603-RD', False, (698.5, 304.8)),
    'LED4': ('KT-0603R', 'Red', 'C2286', 'zudo-pd:LED0603-RD', False, (787.4, 304.8)),
    # interface, provisions, test pads, Screw terminal outputs (row G)
    'J5':   ('PM254V-11-06-H85', 'PM254V-11-06-H85', 'C2832269', 'zudo-pd:HDR-TH_6P-P2.54-V-F', False, (76.2, 355.6)),
    'P1':   ('PogoPad_1x04', 'ATT/PDOK pads', '', 'zudo-pd:PogoEdge_BoardB_1x04_P2.54mm', False, (165.1, 355.6)),
    # Rectangular edge pogo contacts share the existing P1.3 probe return.
    # Each remains a one-pin bare-copper exclusion; no fitted part or net change.
    'TP3':  ('TestPoint', '+13.44V', '', 'zudo-pd:PogoEdge_1x01_1.5x2.5mm', False, (254, 355.6)),
    'TP4':  ('TestPoint', '+6.519V', '', 'zudo-pd:PogoEdge_1x01_1.5x2.5mm', False, (342.9, 355.6)),
    'TP5':  ('TestPoint', '-14.145V', '', 'zudo-pd:PogoEdge_1x01_1.5x2.5mm', False, (431.8, 355.6)),
    'J6':   (*_SCREW, False, (520.7, 355.6)),
    'J7':   (*_SCREW, False, (609.6, 355.6)),
    # Negative pre-rail third can; spare row-J cell clears its vertical label.
    'C12':  (*_C470U_35, False, (520.7, 482.6)),
    # Keyed Eurorack bus headers (row H); pin1/2 -12V red stripe, per renewal decision
    'J10':  (*_EURO16, False, (609.6, 393.7)),
    'J11':  (*_EURO16, False, (787.4, 393.7)),
    'R20': ('RT0603BRD078K2L', '8200R 0.1%', 'C861589', 'zudo-pd:R0603', False, (76.2, 431.8)),
    'R21': ('RT0603BRD07680RL', '680R 0.1%', 'C861519', 'zudo-pd:R0603', False, (165.1, 431.8)),
    'R22': ('RT0603BRD071KL', '1000R 0.1%', 'C110776', 'zudo-pd:R0603', False, (254, 431.8)),
    'R23': ('RT0603BRD073K09L', '3090R 0.1%', 'C861371', 'zudo-pd:R0603', False, (342.9, 431.8)),
    'R24': ('RT0603BRD0733RL', '33R 0.1%', 'C861332', 'zudo-pd:R0603', False, (431.8, 431.8)),
    'R25': ('RT0603BRD071KL', '1000R 0.1%', 'C110776', 'zudo-pd:R0603', False, (520.7, 431.8)),
    # U8 ADJ divider reuses the U6 divider orderables: -1.22 V * (1 + 8880/1000).
    'R26': ('RT0603BRD078K2L', '8200R 0.1%', 'C861589', 'zudo-pd:R0603', False, (609.6, 482.6)),
    'R27': ('RT0603BRD07680RL', '680R 0.1%', 'C861519', 'zudo-pd:R0603', False, (698.5, 482.6)),
    'R28': ('RT0603BRD071KL', '1000R 0.1%', 'C110776', 'zudo-pd:R0603', False, (787.4, 482.6)),
    # AP63201 local ceramic bank and bootstrap, per DS41326 sections 9-13.
    'C36': (*_C10U_50, False, (76.2, 482.6)),
    'C37': (*_C10U_50, False, (165.1, 482.6)),
    'C38': (*_C100N, False, (254, 482.6)),
    'C39': (*_C10U_50, False, (342.9, 482.6)),
    'C46': (*_C10U_50, False, (431.8, 482.6)),
    'C40': ('25SVPF47M', '47uF 25V polymer', 'C136280', 'zudo-pd:CAP-SMD_BD6.3-L6.6-W6.6-FD', False, (609.6, 431.8)),
    'C41': ('25SVPF47M', '47uF 25V polymer', 'C136280', 'zudo-pd:CAP-SMD_BD6.3-L6.6-W6.6-FD', False, (698.5, 431.8)),
    'C42': ('25SVPF47M', '47uF 25V polymer', 'C136280', 'zudo-pd:CAP-SMD_BD6.3-L6.6-W6.6-FD', False, (787.4, 431.8)),
}

NETS = {
    # --- supply and converter nets; intentional renewal deltas are locked ---
    '+15V INPUT': [
        'U2.3', 'U2.2', 'C39.1', 'C46.1', 'C5.1', 'C6.1', 'U3.1', 'C7.1', 'C8.1', 'U4.1', 'C9.1', 'C10.1',
        'J5.1', 'J5.2',                       # A-B interface +15V pair (derived)
    ],
    'U2_SW': ['U2.5', 'L1.1', 'C38.2'],
    'U2_BST': ['U2.6', 'C38.1'],
    '/DC-DC Conversion/+13.44V PRE': [
        'L1.2', 'R1.2', 'C3.1', 'C14.1', 'C20.1', 'C36.1', 'C37.1', 'U6.2', 'U6.1',
        'TP3.1',                              # rail test pad (derived)
    ],
    'Net-(U2-Feedback)': ['U2.1', 'R1.1', 'R2.2'],
    'Net-(D2-K)': ['U3.2', 'D2.1', 'L2.1'],
    '/DC-DC Conversion/+6.519V PRE': [
        'L2.2', 'R3.1', 'C4.1', 'C32.2', 'C15.1', 'C22.1', 'U7.2', 'U7.1',
        'TP4.1',                              # rail test pad (derived)
    ],
    'Net-(U3-Feedback)': ['U3.4', 'R3.2', 'R4.1', 'C32.1'],
    'Net-(D3-K)': ['U4.2', 'D3.1', 'L3.1'],
    # U4 inverting reference: GND/~ON-OFF/TAB bootstrap to -14.145V PRE
    '/DC-DC Conversion/-14.145V PRE': [
        'U4.3', 'U4.5', 'U4.6', 'D3.2', 'C9.2', 'C10.2', 'C11.2', 'R6.2',
        'C16.1', 'C24.2', 'U8.3', 'U8.1', 'U8.6',
        'TP5.1',                              # rail test pad (derived)
        'C12.2',                              # negative output-bank third can (derived)
    ],
    'Net-(U4-Feedback)': ['U4.4', 'R5.1', 'R6.1', 'C33.1'],
    'GND': [
        # baseline rows
        'U2.4', 'R2.1', 'C5.2', 'C6.2', 'C36.2', 'C37.2', 'C39.2', 'C46.2',
        'U3.3', 'U3.5', 'U3.6', 'R4.2', 'C7.2', 'C8.2',
        'L3.2',
        'C14.2', 'C15.2', 'C17.1', 'C18.2', 'C20.2', 'C21.2', 'C22.2', 'C23.2',
        'U6.3', 'U6.6', 'U7.3', 'U7.6', 'U8.2', 'R22.2', 'R25.2', 'R28.2', 'C40.2', 'C41.2', 'C42.1',
        'C16.2', 'C24.1', 'C19.2', 'C25.1',
        # derived: BB-11 buck catch-diode ground returns
        'D2.2',
        # derived: baseline unresolved note 7 (doc-implied DC-DC GND pins)
        'C3.2', 'C4.2', 'C11.1', 'R5.2', 'C33.2',
        # derived: negative output-bank third can (decision neg-rail-cap-bank)
        'C12.1',
        # derived: A-B interface GND pair + P1 probe return
        'J5.5', 'J5.6', 'P1.3',
        # derived: indicator LED ground legs (green 1=K; blue 1=K; red 2=A on GND)
        'LED2.1', 'LED3.1', 'LED4.2',
        # derived: TVS ground legs (TVS3 cathode-to-GND is the locked orientation)
        'TVS1.2', 'TVS2.2', 'TVS3.1',
        # derived: output-stage GND (J6 screw terminal, J10/J11 pins 3-8 GND moat)
        'J6.1',
        'J10.8', 'J10.7', 'J10.6', 'J10.5', 'J10.4', 'J10.3',
        'J11.8', 'J11.7', 'J11.6', 'J11.5', 'J11.4', 'J11.3',
    ],
    'Net-(U6-OUT)': ['U6.4', 'C40.1', 'R20.1', 'C17.2', 'C21.1', 'R7.1', 'PTC1.1'],
    'Net-(U7-OUT)': ['U7.4', 'C41.1', 'R23.1', 'C18.1', 'C23.1', 'R8.1', 'PTC2.1'],
    'Net-(U8-OUT)': ['U8.5', 'R26.1', 'C42.2', 'C19.1', 'C25.2', 'R9.1', 'PTC3.1'],
    'U6 FB upper series': ['R20.2', 'R21.1'],
    'U6 ADJ': ['R21.2', 'R22.1', 'U6.5'],
    'U7 FB upper series': ['R23.2', 'R24.1'],
    'U7 ADJ': ['R24.2', 'R25.1', 'U7.5'],
    'U8 FB upper series': ['R26.2', 'R27.1'],
    'U8 ADJ': ['R27.2', 'R28.1', 'U8.4'],
    # --- derived output-stage rails (post-PTC; baseline lists these as unresolved) ---
    '+12V rail': ['PTC1.2', 'TVS1.1', 'J7.2', 'J10.10', 'J10.9', 'J11.10', 'J11.9'],
    '+5V rail':  ['PTC2.2', 'TVS2.1', 'J7.1', 'J10.12', 'J10.11', 'J11.12', 'J11.11'],
    '-12V rail': ['PTC3.2', 'TVS3.2', 'J6.2', 'J10.2', 'J10.1', 'J11.2', 'J11.1'],
    'GATE rail': ['J10.16', 'J10.15', 'J11.16', 'J11.15'],
    'CV rail':   ['J10.14', 'J10.13', 'J11.14', 'J11.13'],
    # --- derived interface signals (open-drain, no on-board pull-up on either board) ---
    'ATT':  ['J5.3', 'P1.1'],
    'PDOK': ['J5.4', 'P1.2'],
    # --- derived indicator midpoints (all three: pin 1 = K per the LCSC library; LED4 red sits on the negative rail, so its anode is on GND) ---
    'Net-(R7-LED2)': ['R7.2', 'LED2.2'],
    'Net-(R8-LED3)': ['R8.2', 'LED3.2'],
    'Net-(R9-LED4)': ['R9.2', 'LED4.1'],
}

NO_CONNECT = [
    'P1.4',  # declared no-connect per the locked P1 form (decision p1-form)
]

# ERC supply declarations: J5 provides the system return; U2/U3 supply their
# post-inductor intermediate rails, and U4 supplies the negative intermediate.
# These flags declare electrical source roles,
# not verified voltage, headroom, current capacity, or measured regulation.
# Supply declarations occupy a dedicated footer row, clear of test-point labels
# and the connector bodies. Their net identities remain unchanged.
ERC_POWER_FLAGS = {
    "GND": (76.2, 546.1),
    "+15V INPUT": (165.1, 546.1),
    "/DC-DC Conversion/+13.44V PRE": (254.0, 546.1),
    "/DC-DC Conversion/+6.519V PRE": (431.8, 546.1),
    "/DC-DC Conversion/-14.145V PRE": (520.7, 546.1),
}

# Keep vertical pin labels readable by placing these references and values to
# the side. U6/U7 values sit below their two downward GND labels.
LABEL_OVERRIDES = {
    'J6': {'Reference': (538.48, 353.06), 'Value': (538.48, 358.14)},
    'J7': {'Reference': (627.38, 353.06), 'Value': (627.38, 358.14)},
    'C4': {'Reference': (180.34, 149.86), 'Value': (180.34, 154.94)},
    'C5': {'Reference': (269.24, 149.86), 'Value': (269.24, 154.94)},
    'C7': {'Reference': (447.04, 149.86), 'Value': (447.04, 154.94)},
    'C11': {'Reference': (802.64, 149.86), 'Value': (802.64, 154.94)},
    'C12': {'Reference': (535.94, 480.06), 'Value': (535.94, 485.14)},
    'C21': {'Reference': (713.74, 200.66), 'Value': (713.74, 205.74)},
    'C22': {'Reference': (802.64, 200.66), 'Value': (802.64, 205.74)},
    'C23': {'Reference': (91.44, 251.46), 'Value': (91.44, 256.54)},
    'C24': {'Reference': (180.34, 251.46), 'Value': (180.34, 256.54)},
    'C25': {'Reference': (269.24, 251.46), 'Value': (269.24, 256.54)},
    'TP3': {'Reference': (269.24, 353.06), 'Value': (269.24, 358.14)},
    'TP4': {'Reference': (358.14, 353.06), 'Value': (358.14, 358.14)},
    'TP5': {'Reference': (447.04, 353.06), 'Value': (447.04, 358.14)},
    'U6': {'Value': (76.2, 125.73)},
    'U7': {'Value': (165.1, 125.73)},
}
