/**
 * Sidebar configuration file.
 *
 * Keys correspond to headerNav categoryMatch values.
 * If a section has no config here, it uses auto-generated filesystem sidebar.
 */

export interface SidebarLink {
  type: "link";
  label: string;
  href: string;
}

export interface SidebarDoc {
  type: "doc";
  id: string;
  label?: string;
}

export interface SidebarCategory {
  type: "category";
  label: string;
  items: SidebarItem[];
  collapsed?: boolean;
  sortOrder?: "asc" | "desc";
}

export interface SidebarAutogenerated {
  type: "autogenerated";
  dirName?: string;
}

export type SidebarItem =
  | SidebarDoc
  | SidebarLink
  | SidebarCategory
  | SidebarAutogenerated
  | string;

export interface SidebarsConfig {
  [sectionKey: string]: SidebarItem[] | undefined;
}

const sidebars: SidebarsConfig = {
  overview: [
    "overview",
    "overview/overview",
    "overview/circuit-diagrams",
    "overview/bom",
    "overview/mechanical-design",
    "overview/usb-pd-adapter",
  ],
  components: [
    "components",
    "components/usb-c-connector",
    "components/stusb4500",
    "components/ao3401a",
    "components/usblc6-2sc6",
    "components/esda25l",
    "components/ch224d",
    "components/lm2596s-adj",
    "components/l7812cv",
    "components/l7805abd2t",
    "components/cj7912",
    "components/ptc-12v",
    "components/ptc-5v",
    "components/ptc-12v-neg",
    "components/smaj15a",
    "components/sd05",
    "components/faston-terminal",
  ],
  learning: [
    "learning",
    "learning/gnd-component-placement",
    "learning/gndd-gnda-split-ground",
    "learning/ch224d-usb-pd-controller",
    "learning/usb-type-c-pinout",
    "learning/usb-pd-vs-traditional-usb",
    "learning/open-drain-pg-pin",
    "learning/p-channel-mosfet-load-switch",
    "learning/esd-protection-tvs-diodes",
    "learning/buck-converter-feedback",
    "learning/inductor-voltage-reversal",
    "learning/pcb-layout-power-circuits",
    "learning/trace-width-copper-weight",
    "learning/transformer-polarity-flyback",
    "learning/linear-regulator-capacitors",
    "learning/two-stage-dc-dc-ldo-architecture",
    "learning/protection-fuse-strategy",
    "learning/eurorack-power-distribution",
  ],
  "how-to": [
    "how-to",
    "how-to/kicad-workflow",
    "how-to/kicad-parts-download",
    "how-to/create-footprint-svg",
    "how-to/create-circuit-svg",
  ],
  misc: ["misc", "misc/footprint-preview"],
  inbox: [
    "inbox",
    "inbox/current-status",
    "inbox/quick-reference",
    "inbox/pcba-v1-debug",
    "inbox/nvm-programming",
  ],
};

export default sidebars;
