/**
 * Sidebar configuration file.
 *
 * Keys correspond to headerNav categoryMatch values.
 * If a section has no config here, it uses auto-generated filesystem sidebar.
 */

export interface SidebarLink {
  type: "link";
  label: string;
  href: string;
}

export interface SidebarDoc {
  type: "doc";
  id: string;
  label?: string;
}

export interface SidebarCategory {
  type: "category";
  label: string;
  items: SidebarItem[];
  collapsed?: boolean;
  sortOrder?: "asc" | "desc";
}

export interface SidebarAutogenerated {
  type: "autogenerated";
  dirName?: string;
}

export type SidebarItem =
  | SidebarDoc
  | SidebarLink
  | SidebarCategory
  | SidebarAutogenerated
  | string;

export interface SidebarsConfig {
  [sectionKey: string]: SidebarItem[] | undefined;
}

const sidebars: SidebarsConfig = {
  "overview": [
    { type: "autogenerated" },
  ],
  "components": [
    { type: "autogenerated" },
  ],
  "learning": [
    { type: "autogenerated" },
  ],
  "how-to": [
    { type: "autogenerated" },
  ],
  "misc": [
    { type: "autogenerated" },
  ],
  "inbox": [
    { type: "autogenerated" },
  ],
};

export default sidebars;
