M48
; DRILL file KiCad 10.0.0 date 2026-09-21T23:19:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T23:19:19+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X4.0Y81.0
X4.0Y4.0
X106.0Y81.0
X106.0Y4.0
T2
X3.5Y69.0
X3.5Y50.0
X32.1Y60.2
M30
