import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir, realpath, stat, mkdtemp, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { createRequire } from 'node:module';
import { root, corpus, json, packageRoot, internal } from './compatibility-helpers.mjs';
const {model,mapped,index}=await corpus(root);
const canonical=x=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x;
const hash=x=>createHash('sha256').update(JSON.stringify(canonical(x))).digest('hex');
test('every decoded published claim matches the reviewed legacy model',async()=>{
 const baseline=await json(join(root,'circuit/tests/runtime-semantic-baseline.json'));
 assert.equal(Object.keys(baseline.records).length,60);
 assert.deepEqual(model.records.map(r=>r.identity.slug).sort(),Object.keys(baseline.records).sort());
 for(const record of model.records)for(const [field,expected]of Object.entries(baseline.records[record.identity.slug]))assert.equal(hash(record[field]),expected,`${record.identity.slug}.${field}`);
 assert.equal(hash(model.integration),baseline.integration,'all 11 rules, conditions, calculations, evidence stages and refusals');
});
test('all 64 generated routes retain every baseline evidence anchor and use the package marker/notice',async()=>{
 const baseline=await json(join(root,'circuit/tests/runtime-anchor-baseline.json'));
 assert.equal(Object.keys(baseline).length,64);
 const {GENERATED_MARKER,LEGACY_MARKERS}=await internal('core/page.js');
 assert.ok(LEGACY_MARKERS.includes('# GENERATED by doc/component-docs — do not edit; run `pnpm generate:components`'));
 for(const[path,ids]of Object.entries(baseline)){
  const page=await readFile(join(root,path),'utf8');
  for(const id of ids)assert.ok(page.includes(`id="${id}"`),`${path} lost ${id}`);
  assert.ok(page.includes(GENERATED_MARKER),path);
  assert.ok(page.includes('Generated from the component evidence records'),path);
 }
});
test('root and doc resolve the same patched module and runtime behavior',async()=>{
 const fromRoot=createRequire(join(root,'package.json')),fromDoc=createRequire(join(root,'doc/package.json'));
 const a=await realpath(fromRoot.resolve('@takazudo/zudo-circuit-doc/package.json')),b=await realpath(fromDoc.resolve('@takazudo/zudo-circuit-doc/package.json'));
 assert.equal(a,b);assert.match(a,/patch_hash=/u);
 assert.equal((await json(a)).version,'0.1.0');
 const schema=await readFile(join(packageRoot,'lib/config/schema.js'),'utf8');assert.match(schema,/candidates: optional/u);assert.match(schema,/mpnFromValueLcsc/u);
 const reference=await readFile(join(packageRoot,'lib/provider/v1/references.js'),'utf8');assert.match(reference,/document exception names missing record/u);
 for(const path of ['doc/pnpm-lock.yaml','doc/pnpm-workspace.yaml'])await assert.rejects(stat(join(root,path)),{code:'ENOENT'});
});
test('all existing public files are individually reviewed; preview ownership stays separate',async()=>{
 const assets=await json(join(root,'circuit/publication/assets.json'));const allowed=new Map(assets.assets.map(a=>[a.path,a.reason]));
 async function visit(dir){for(const entry of await readdir(join(root,'doc/public',dir),{withFileTypes:true})){const path=dir?`${dir}/${entry.name}`:entry.name;if(entry.isDirectory())await visit(path);else if(!path.startsWith('assets/component-previews/')){assert.ok(allowed.has(path),path);assert.ok(allowed.get(path).length>40,path);}}}
 await visit('');for(const path of allowed.keys())assert.ok((await stat(join(root,'doc/public',path))).isFile(),path);
 assert.ok(allowed.has('_redirects'));assert.ok(assets.assets.filter(a=>a.path.startsWith('datasheets/')).every(a=>a.reason.includes('historical')));
});
test('thin host imports package SSR, islands and stylesheet; project browser keeps all 12 cases',async()=>{
 const bindings=await readFile(join(root,'doc/src/chrome-bindings.tsx'),'utf8');assert.match(bindings,/circuitDocMdxExtras/u);assert.doesNotMatch(bindings,/component-docs\/ui/u);
 const route=await readFile(join(root,'doc/pages/docs/[[...slug]].tsx'),'utf8');assert.match(route,/_circuit-doc-islands/u);assert.match(route,/defineChromeBindings\(\{ DocHistory \}\)/u);
 const seed=await readFile(join(root,'doc/pages/lib/_circuit-doc-islands.ts'),'utf8');assert.match(seed,/@takazudo\/zudo-circuit-doc\/islands/u);
 const css=await readFile(join(root,'doc/src/styles/global.css'),'utf8');assert.ok(css.indexOf('zudo-circuit-doc/styles.css')>css.indexOf('zudo-doc/features.css'));assert.doesNotMatch(css,/\.zld-/u);
 const smoke=await readFile(join(root,'circuit/scripts/model-viewer-browser-smoke.mjs'),'utf8');assert.equal([...smoke.matchAll(/\{ kind:/g)].length,12);assert.match(smoke,/documentResolved: false/u);assert.match(smoke,/not exact manufacturer CAD/u);assert.match(smoke,/\[1440, 375\]/u);assert.match(smoke,/\["light", "dark"\]/u);assert.doesNotMatch(smoke,/\.zld-/u);
 assert.equal(mapped.config.browserSmoke.representatives.length,3);
 const styles=await readFile(join(packageRoot,'styles.css'),'utf8');assert.match(styles,/\.zcd-evidence-table\s*\{[^}]*overflow-x:\s*auto/u);assert.match(styles,/\.zcd-evidence-table table\s*\{[^}]*min-width:/u);
});
test('root gates precede writers, host build stays zfb-only and dev uses package watch',async()=>{
 const p=await json(join(root,'package.json')),d=await json(join(root,'doc/package.json'));
 assert.match(p.scripts['circuit:prepare'],/^pnpm circuit:project-check && zudo-circuit-doc models && zudo-circuit-doc generate$/u);
 assert.match(p.scripts.build,/^pnpm circuit:prepare &&/u);assert.match(p.scripts['circuit:project-check'],/validate.py --strict.*check_forward_tests.py --strict/u);
 assert.equal(d.scripts.build,'zfb build');assert.match(d.scripts['dev:circuit'],/zudo-circuit-doc generate --watch/u);
 for(const key of ['build','dev','generate:components','generate:models','dev:components'])assert.doesNotMatch(d.scripts[key],/component-docs\//u,key);
 assert.match(p.scripts.check,/footprints check/u);assert.match(p.scripts.check,/models --check/u);assert.match(p.scripts['check:site'],/strict-anchors --strict-broken/u);assert.match(p.scripts['check:site'],/check-built-fragment-links/u);assert.match(p.scripts['check:site'],/check-zfb-link-warnings/u);
});
