M48
; DRILL file {KiCad 9.0.6} date 2026-02-04T05:23:08+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-04T05:23:08+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X1.0Y-7.0
X1.0Y-92.0
X44.5Y-73.0
X53.0Y-35.5
X53.0Y-55.0
X54.25Y-7.0
X69.0Y-92.0
M30
